service: lambda-sqs
frameworkVersion: '3'

provider:
  name: aws
  runtime: go1.x
  timeout: 6
  memorySize: 256

  environment:
    env_test: "value-test"

package:
  patterns:
    - '!./**'
    - ./bin/**

functions:
  push:
    handler: bin/push
    events:
      - httpApi:
          path: /push
          method: post
  receive:
    handler: bin/receive
    # events:
    #   - httpApi:
    #       path: /push
    #       method: post