service: lambda-go
frameworkVersion: '3'

provider:
  name: aws
  runtime: go1.x
  timeout: 6
  memorySize: 256
  region: ap-southeast-1

  environment:
    DB_USER: ""
    DB_PASS: ""
    DB_HOST: ""
    DB_SERVICE: ""

package:
  patterns:
    - '!./**'
    - ./bin/**

functions:
  create:
    handler: bin/create
    events:
      - httpApi:
          path: /create
          method: post
  delete:
    handler: bin/delete
    events:
      - httpApi:
          path: /delete
          method: post
  read:
    handler: bin/read
    events:
      - httpApi:
          path: /read
          method: get
  update:
    handler: bin/update
    events:
      - httpApi:
          path: /update
          method: post