# .goreleaser.yml
project_name: dtm
builds:
  - id: dtm_amd64
    env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
    dir: .
    main: main.go
    ldflags:
      - -s -w -X main.Version=v{{.Version}}
  - id: dtm_arm64
    env: [CGO_ENABLED=0]
    goos:
      - darwin
    goarch:
      - arm64
    dir: .
    main: main.go
    ldflags:
      - -s -w -X main.Version=v{{.Version}}
