// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.17.3
// source: busi/busi.proto

package busi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BusiReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Amount         int64  `protobuf:"varint,1,opt,name=Amount,proto3" json:"Amount,omitempty"`
	UserID         int64  `protobuf:"varint,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	TransOutResult string `protobuf:"bytes,3,opt,name=TransOutResult,proto3" json:"TransOutResult,omitempty"`
	TransInResult  string `protobuf:"bytes,4,opt,name=TransInResult,proto3" json:"TransInResult,omitempty"`
}

func (x *BusiReq) Reset() {
	*x = BusiReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_busi_busi_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BusiReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BusiReq) ProtoMessage() {}

func (x *BusiReq) ProtoReflect() protoreflect.Message {
	mi := &file_busi_busi_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BusiReq.ProtoReflect.Descriptor instead.
func (*BusiReq) Descriptor() ([]byte, []int) {
	return file_busi_busi_proto_rawDescGZIP(), []int{0}
}

func (x *BusiReq) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *BusiReq) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *BusiReq) GetTransOutResult() string {
	if x != nil {
		return x.TransOutResult
	}
	return ""
}

func (x *BusiReq) GetTransInResult() string {
	if x != nil {
		return x.TransInResult
	}
	return ""
}

type BusiReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
}

func (x *BusiReply) Reset() {
	*x = BusiReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_busi_busi_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BusiReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BusiReply) ProtoMessage() {}

func (x *BusiReply) ProtoReflect() protoreflect.Message {
	mi := &file_busi_busi_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BusiReply.ProtoReflect.Descriptor instead.
func (*BusiReply) Descriptor() ([]byte, []int) {
	return file_busi_busi_proto_rawDescGZIP(), []int{1}
}

func (x *BusiReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_busi_busi_proto protoreflect.FileDescriptor

var file_busi_busi_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x62, 0x75, 0x73, 0x69, 0x2f, 0x62, 0x75, 0x73, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x04, 0x62, 0x75, 0x73, 0x69, 0x22, 0x87, 0x01, 0x0a, 0x07, 0x42, 0x75, 0x73, 0x69,
	0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x44, 0x12, 0x26, 0x0a, 0x0e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x4f, 0x75, 0x74, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x4f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x49, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0d, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x49, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x22, 0x25, 0x0a, 0x09, 0x42, 0x75, 0x73, 0x69, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18,
	0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0xc8, 0x01, 0x0a, 0x04, 0x42, 0x75, 0x73,
	0x69, 0x12, 0x31, 0x0a, 0x0d, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x49, 0x6e, 0x52, 0x65, 0x76, 0x65,
	0x72, 0x74, 0x12, 0x0d, 0x2e, 0x62, 0x75, 0x73, 0x69, 0x2e, 0x42, 0x75, 0x73, 0x69, 0x52, 0x65,
	0x71, 0x1a, 0x0f, 0x2e, 0x62, 0x75, 0x73, 0x69, 0x2e, 0x42, 0x75, 0x73, 0x69, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x00, 0x12, 0x32, 0x0a, 0x0e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x4f, 0x75, 0x74,
	0x52, 0x65, 0x76, 0x65, 0x72, 0x74, 0x12, 0x0d, 0x2e, 0x62, 0x75, 0x73, 0x69, 0x2e, 0x42, 0x75,
	0x73, 0x69, 0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x62, 0x75, 0x73, 0x69, 0x2e, 0x42, 0x75, 0x73,
	0x69, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x2b, 0x0a, 0x07, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x49, 0x6e, 0x12, 0x0d, 0x2e, 0x62, 0x75, 0x73, 0x69, 0x2e, 0x42, 0x75, 0x73, 0x69, 0x52,
	0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x62, 0x75, 0x73, 0x69, 0x2e, 0x42, 0x75, 0x73, 0x69, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x2c, 0x0a, 0x08, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x4f, 0x75,
	0x74, 0x12, 0x0d, 0x2e, 0x62, 0x75, 0x73, 0x69, 0x2e, 0x42, 0x75, 0x73, 0x69, 0x52, 0x65, 0x71,
	0x1a, 0x0f, 0x2e, 0x62, 0x75, 0x73, 0x69, 0x2e, 0x42, 0x75, 0x73, 0x69, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x00, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x2f, 0x62, 0x75, 0x73, 0x69, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_busi_busi_proto_rawDescOnce sync.Once
	file_busi_busi_proto_rawDescData = file_busi_busi_proto_rawDesc
)

func file_busi_busi_proto_rawDescGZIP() []byte {
	file_busi_busi_proto_rawDescOnce.Do(func() {
		file_busi_busi_proto_rawDescData = protoimpl.X.CompressGZIP(file_busi_busi_proto_rawDescData)
	})
	return file_busi_busi_proto_rawDescData
}

var file_busi_busi_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_busi_busi_proto_goTypes = []interface{}{
	(*BusiReq)(nil),   // 0: busi.BusiReq
	(*BusiReply)(nil), // 1: busi.BusiReply
}
var file_busi_busi_proto_depIdxs = []int32{
	0, // 0: busi.Busi.TransInRevert:input_type -> busi.BusiReq
	0, // 1: busi.Busi.TransOutRevert:input_type -> busi.BusiReq
	0, // 2: busi.Busi.TransIn:input_type -> busi.BusiReq
	0, // 3: busi.Busi.TransOut:input_type -> busi.BusiReq
	1, // 4: busi.Busi.TransInRevert:output_type -> busi.BusiReply
	1, // 5: busi.Busi.TransOutRevert:output_type -> busi.BusiReply
	1, // 6: busi.Busi.TransIn:output_type -> busi.BusiReply
	1, // 7: busi.Busi.TransOut:output_type -> busi.BusiReply
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_busi_busi_proto_init() }
func file_busi_busi_proto_init() {
	if File_busi_busi_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_busi_busi_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BusiReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_busi_busi_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BusiReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_busi_busi_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_busi_busi_proto_goTypes,
		DependencyIndexes: file_busi_busi_proto_depIdxs,
		MessageInfos:      file_busi_busi_proto_msgTypes,
	}.Build()
	File_busi_busi_proto = out.File
	file_busi_busi_proto_rawDesc = nil
	file_busi_busi_proto_goTypes = nil
	file_busi_busi_proto_depIdxs = nil
}
