apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dtm.fullname" . }}-conf
  labels:
    {{- include "dtm.labels" . | nindent 4 }}
data:
  config.yaml: |-
    {{- .Values.configuration | nindent 4 }}