service: golang-migration
frameworkVersion: '3'

provider:
  name: aws
  runtime: provided.al2 # <- change from go1.x to provided.al2
  architecture: arm64   # <- change from x86_64 to arm64
  region: ap-southeast-1

functions:
  hello:
    # handler: bin/x86 # old
    handler: bootstrap # new
    events:
      - httpApi:
          # path: /x86 # old
          path: /arm64 # new
          method: get
